- name: limit
  in: query
  description: Number of items returned. If not specified, all instances are returned.
  schema:
    type: integer
- name: offset
  in: query
  description: Number of items to skip. If not specified, none items are skipped.
  schema:
    type: integer
